### ISSUE TITLE
update SignalR samples to .NET Core 2.1 

### ISSUE THREAD

**Issue by christiannagel** [ProfessionalCSharp/ProfessionalCSharp7#39]
update the SignalR samples to the release of .NET Core 2.1

**Comment by christiannagel** [comment]
bonus chapter 3, directory SignalRAndWebHooks

**Comment by christiannagel** [comment]
updated with commit a437d20fd7048da2a2b7628356fb9aa4e811f3b7

**Comment by GreenEyedAndy** [comment]
Hi Christian,
is it right that the string "EOS" can not be part of a message? So, if I want to send all sort of text maybe binary then I have to escape my control characters? Or is there another way?

**Comment by christiannagel** [comment]
@GreenEyedAndy - where do you have the information about the **EOS** string from? As part of the communication it shouldn't be an issue to send this string.

**Comment by Andyriod** [comment]
@christiannagel - no you missunderstood me. In your example you use ;EOS as the end of sequence marker. I just want to ask how you handle the situation if a chatclient is sending the following text: 'I own the following cars a VW;EOS a VOLVO;V90 and a MERCEDES;VITO'. Sure it is a bit constructed, but you see a chatclient can not send any text!

**Comment by GreenEyedAndy** [comment]
@christiannagel  - no you missunderstood me. In your example you use ;EOS as the end of sequence marker. I just want to ask how you handle the situation if a chatclient is sending the following text: 'I own the following cars a VW;EOS a VOLVO;V90 and a MERCEDES;VITO'. Sure it is a bit constructed, but you see a chatclient can not send any text!

**Comment by christiannagel** [comment]
@GreenEyedAndy - you're right. I totally forgot the EOS in the sample. The sample is probably too simplified. As I'm updating the SignalR sample and the downloadable PDF file, I'm also updating this in the sample code by sending a different message.
