### ISSUE TITLE
Is Information On Bower Outdated?

### ISSUE THREAD

**Issue by RobPaulson** [ProfessionalCSharp/ProfessionalCSharp7#45]
Chapter 30 - ASP.NET CORE talks about ASP.NET Core MVC web applications including Bower by default.  But when I used VS2017 to create one, I don't see any Dependencies on Bower.  When I open the WebSampleApp it does build, but when I try to update bootstrap or jquery through Bower, I receive an error:

_EINVRES Request to https://bower.herokuapp.com/packages/bootstrap failed with 502_

Online I was told that I should update to the latest version of Bower to fix this.  When attempting to do that, I found that bower is now deprecated and not recommended for use in new project.  Instead it says to 'Please consider Yarn and Webpack or Parcel'.

I'm a n0ob, so my apologies if I'm confused or wrong.

**Comment by christiannagel** [comment]
Sorry for the issues with Bower.
I've written a blog article on this: https://csharp.christiannagel.com/2018/06/13/librarymanager/
With Visual Studio 2018 Update 8 (currently in preview), you can use the **Library Manager**. 
I'll update the ASP.NET Core samples and https://github.com/ProfessionalCSharp/ProfessionalCSharp7/blob/master/BookUpdates.md for using it with Visual Studio 2018 Update 8.
Thanks,
Christian

**Comment by christiannagel** [comment]
@RobPaulson - I've updated the code for the ASP.NET Core sample in the [librarymanager branch](https://github.com/ProfessionalCSharp/ProfessionalCSharp7/tree/librarymanager). I will do a pull request to the master branch as Visual Studio 2017 Update 8 is released - currently in [preview](https://visualstudio.microsoft.com/vs/preview/).

Hope this helps.

**Comment by christiannagel** [comment]
Visual Studio 2017 Update 8 is released, and pull request done. 
Closing this issue. In case you've questions on Bower/Library Manager, please reopen or create a new issue.
